#!/usr/bin/env python3
"""Export an approved selector cache to a Playwright Page Object Model (TS).

Closes the loop with the repo's other skills: klew resolves
human-approved, runtime-verified locators; this turns them into a typed Page
Object so `yilsf`-generated specs import real selectors instead of guessing, and
`testguard` can review specs built on them.

    export_pom.py --app <slug> [--out path.ts] [--min-confidence 0.0]

Logical names group into classes by their first dotted segment:
    login.email        -> class LoginPage   { get email()  }
    login.submit       -> class LoginPage   { get submit() }
    checkout.placeOrder-> class CheckoutPage { get placeOrder() }

`getBy*` selectors pass through as `this.page.getBy...`; raw CSS becomes
`this.page.locator('...')`. Stale/ambiguous or low-confidence entries are
skipped (and reported) so the POM only exposes locators worth trusting.
"""

from __future__ import annotations

import argparse
import sys

from _common import app_dir, load_cache
from scene_adapters import point_expr


def _member(rest: list[str]) -> str:
    parts = [p for seg in rest for p in seg.replace("-", "_").split("_")]
    if not parts:
        return "el"
    head, *tail = parts
    name = head + "".join(w[:1].upper() + w[1:] for w in tail)
    return name if name.isidentifier() else "_" + name


def _class_name(group: str) -> str:
    words = group.replace("-", "_").split("_")
    return "".join(w[:1].upper() + w[1:] for w in words if w) + "Page"


def _indent(text: str, spaces: int) -> str:
    """Indent every line after the first by `spaces` (for embedding a JS block)."""
    pad = " " * spaces
    head, *tail = text.split("\n")
    return "\n".join([head] + [pad + t for t in tail])


def _js_str(value: str) -> str:
    return value.replace("\\", "\\\\").replace("'", "\\'")


def _frame_prefix(frame) -> str:
    """A frameLocator(...) chain for an element inside one or more iframes."""
    if not frame:
        return "this.page"
    frames = [frame] if isinstance(frame, str) else list(frame)
    return "this.page" + "".join(f".frameLocator('{_js_str(f)}')" for f in frames)


def _locator_expr(entry: dict) -> str:
    """Build the locator, scoped into any iframe chain the entry records.

    Open shadow DOM needs nothing special — role/label/text locators pierce it.
    iframes do: the element lives inside `frameLocator(...)`, recorded as `frame`
    (a single selector, or a list for nested frames).
    """
    s = entry["selector"].strip()
    base = _frame_prefix(entry.get("frame"))
    if s.startswith("getBy"):
        return f"{base}.{s}"
    return f"{base}.locator('{_js_str(s)}')"


def main() -> None:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("--app", required=True, help="application slug")
    ap.add_argument("--out", default=None, help="output .ts path (default under knowledge/<app>/)")
    ap.add_argument(
        "--min-confidence", type=float, default=0.0, help="skip entries below this score"
    )
    args = ap.parse_args()

    cache = load_cache(args.app)
    selectors = cache.get("selectors", {})
    if not selectors:
        sys.exit(f"error: no selectors cached for app {args.app!r}")

    groups: dict[str, list[tuple[str, dict]]] = {}
    skipped: list[str] = []
    for name, entry in sorted(selectors.items()):
        if entry.get("status") in {"stale", "ambiguous"}:
            skipped.append(f"{name} ({entry['status']})")
            continue
        if float(entry.get("confidence", 1.0)) < args.min_confidence:
            skipped.append(f"{name} (confidence {entry.get('confidence')})")
            continue
        group, *rest = name.split(".")
        groups.setdefault(group, []).append((_member(rest or [group]), entry))

    if not groups:
        sys.exit("error: nothing to export after filtering (all stale/ambiguous/low-confidence)")

    lines = [
        "// AUTO-GENERATED by klew/scripts/export_pom.py — do not edit by hand.",
        f"// App: {cache.get('app', args.app)}   Base URL: {cache.get('base_url', '')}",
        f"// Generated from human-approved selectors (updated {cache.get('updated', '')}).",
        "import { type Page, type Locator } from '@playwright/test';",
        "",
    ]
    for group in sorted(groups):
        lines.append(f"export class {_class_name(group)} {{")
        lines.append("  constructor(private readonly page: Page) {}")
        lines.append("")
        seen: set[str] = set()
        for member, entry in groups[group]:
            m = member
            n = 1
            while m in seen:  # guard against camelCase collisions
                n += 1
                m = f"{member}{n}"
            seen.add(m)
            if entry.get("tier") == "scene":
                # A canvas/WebGL node has no DOM element, so it is exposed as an
                # async click action (scene model -> point -> real mouse click)
                # rather than a Locator getter.
                sc = entry["scene"]
                lines.append(
                    f"  // tier=scene engine={sc.get('engine')} "
                    f"confidence={entry.get('confidence')} "
                    "[scene: canvas/WebGL node — no DOM; addressed by identity]"
                )
                expr = _indent(point_expr(sc), 6)
                lines.append(f"  async {m}(): Promise<void> {{")
                lines.append(f"    const pt = await this.page.evaluate({expr});")
                lines.append("    await this.page.mouse.click(pt.x, pt.y);")
                lines.append("  }")
                continue
            note = f"  // tier={entry.get('tier')} confidence={entry.get('confidence')}"
            if entry.get("a11y_flag"):
                note += " [a11y: non-user-facing locator]"
            if entry.get("frame"):
                note += f" [iframe: {entry['frame']}]"
            if entry.get("shadow"):
                note += " [shadow DOM]"
            lines.append(note)
            lines.append(f"  get {m}(): Locator {{ return {_locator_expr(entry)}; }}")
        lines.append("}")
        lines.append("")

    out = args.out or str(app_dir(args.app) / f"{args.app}.pom.ts")
    app_dir(args.app).mkdir(parents=True, exist_ok=True)
    with open(out, "w") as fh:
        fh.write("\n".join(lines))

    print(f"Wrote {out}")
    print(f"  classes: {', '.join(_class_name(g) for g in sorted(groups))}")
    if skipped:
        print(f"  skipped: {', '.join(skipped)}")


if __name__ == "__main__":
    main()
