// AUTO-GENERATED by klew/scripts/export_pom.py — do not edit by hand.
// App: konva-demo   Base URL: http://127.0.0.1:8123
// Generated from human-approved selectors (updated 2026-07-22).
import { type Page, type Locator } from '@playwright/test';

export class ShapesPage {
  constructor(private readonly page: Page) {}

  // tier=scene engine=konva confidence=0.7 [scene: canvas/WebGL node — no DOM; addressed by identity]
  async blue(): Promise<void> {
    const pt = await this.page.evaluate(() => {
        const s = window.__konva;
        if (!s) throw new Error('scene/konva: instance not found');
        const arr = s.find('Shape'); const list = arr.toArray ? arr.toArray() : Array.from(arr); const key = "name"; const get = key === 'name' ? (n) => n.name() : key === 'id' ? (n) => n.id() : (n) => n.getAttr(key); 
        const node = list.find(n => String(get(n)).toLowerCase() === "Blue".toLowerCase());
        if (!node) throw new Error('scene/konva: no ' + key + '=' + "Blue");
        const box = node.getClientRect();
        const r = s.container().getBoundingClientRect();
        const pt = { x: Math.round(r.left + box.x + box.width / 2),
                     y: Math.round(r.top + box.y + box.height / 2) };
        window.__ksel = pt; return pt;
      });
    await this.page.mouse.click(pt.x, pt.y);
  }
  // tier=scene engine=konva confidence=0.7 [scene: canvas/WebGL node — no DOM; addressed by identity]
  async green(): Promise<void> {
    const pt = await this.page.evaluate(() => {
        const s = window.__konva;
        if (!s) throw new Error('scene/konva: instance not found');
        const arr = s.find('Shape'); const list = arr.toArray ? arr.toArray() : Array.from(arr); const key = "name"; const get = key === 'name' ? (n) => n.name() : key === 'id' ? (n) => n.id() : (n) => n.getAttr(key); 
        const node = list.find(n => String(get(n)).toLowerCase() === "Green".toLowerCase());
        if (!node) throw new Error('scene/konva: no ' + key + '=' + "Green");
        const box = node.getClientRect();
        const r = s.container().getBoundingClientRect();
        const pt = { x: Math.round(r.left + box.x + box.width / 2),
                     y: Math.round(r.top + box.y + box.height / 2) };
        window.__ksel = pt; return pt;
      });
    await this.page.mouse.click(pt.x, pt.y);
  }
}
