// AUTO-GENERATED by klew/scripts/export_pom.py — do not edit by hand.
// App: parabank   Base URL: https://parabank.parasoft.com/parabank/
// Generated from human-approved selectors (updated 2026-09-02).
import { type Page, type Locator } from '@playwright/test';

export class FindtransPage {
  constructor(private readonly page: Page) {}

  // tier=css confidence=0.4 [a11y: non-user-facing locator]
  get byAmount(): Locator { return this.page.locator('#findByAmount'); }
  // tier=css confidence=0.4 [a11y: non-user-facing locator]
  get byDate(): Locator { return this.page.locator('#findByDate'); }
  // tier=css confidence=0.4 [a11y: non-user-facing locator]
  get date(): Locator { return this.page.locator('#transactionDate'); }
}

export class LoginPage {
  constructor(private readonly page: Page) {}

  // tier=css confidence=0.4 [a11y: non-user-facing locator]
  get password(): Locator { return this.page.locator('input[name="password"]'); }
  // tier=role confidence=1.0
  get submit(): Locator { return this.page.getByRole('button', { name: 'Log In' }); }
  // tier=css confidence=0.4 [a11y: non-user-facing locator]
  get username(): Locator { return this.page.locator('input[name="username"]'); }
}

export class NavPage {
  constructor(private readonly page: Page) {}

  // tier=role confidence=1.0
  get accountsOverview(): Locator { return this.page.getByRole('link', { name: 'Accounts Overview' }); }
  // tier=role confidence=1.0
  get findTransactions(): Locator { return this.page.getByRole('link', { name: 'Find Transactions' }); }
  // tier=role confidence=1.0
  get transferFunds(): Locator { return this.page.getByRole('link', { name: 'Transfer Funds' }); }
}

export class TransferPage {
  constructor(private readonly page: Page) {}

  // tier=label-text confidence=0.9
  get activityLink(): Locator { return this.page.getByText('See Account Activity for more'); }
  // tier=css confidence=0.4 [a11y: non-user-facing locator]
  get amount(): Locator { return this.page.locator('#amount'); }
  // tier=role confidence=1.0
  get confirmHeading(): Locator { return this.page.getByRole('heading', { name: 'Transfer Complete!' }); }
  // tier=label-text confidence=0.9
  get confirmMessage(): Locator { return this.page.getByText('has been transferred from account'); }
  // tier=css confidence=0.4 [a11y: non-user-facing locator]
  get fromAccount(): Locator { return this.page.locator('#fromAccountId'); }
  // tier=role confidence=1.0
  get submit(): Locator { return this.page.getByRole('button', { name: 'Transfer' }); }
  // tier=css confidence=0.4 [a11y: non-user-facing locator]
  get toAccount(): Locator { return this.page.locator('#toAccountId'); }
}
