// AUTO-GENERATED by klew/scripts/export_pom.py — do not edit by hand.
// App: echarts-demo   Base URL: http://127.0.0.1:8123
// Generated from human-approved selectors (updated 2026-07-22).
import { type Page, type Locator } from '@playwright/test';

export class BarsPage {
  constructor(private readonly page: Page) {}

  // tier=scene engine=echarts confidence=0.7 [scene: canvas/WebGL node — no DOM; addressed by identity]
  async apr(): Promise<void> {
    const pt = await this.page.evaluate(() => {
        const c = window.__echart;
        if (!c) throw new Error('scene/echarts: instance not found');
        const o = c.getOption();
        const cats = (o.xAxis && o.xAxis[0] && o.xAxis[0].data) || [];
        const i = cats.findIndex(v => String(v).toLowerCase() === "Apr".toLowerCase());
        if (i < 0) throw new Error('scene/echarts: no category ' + "Apr");
        const val = o.series[0].data[i];
        const p = c.convertToPixel({ seriesIndex: 0 }, [i, val]);
        const base = c.convertToPixel({ seriesIndex: 0 }, [i, 0]);
        const y = base ? (p[1] + base[1]) / 2 : p[1];
        const r = c.getDom().getBoundingClientRect();
        const pt = { x: Math.round(r.left + p[0]), y: Math.round(r.top + y) };
        window.__ksel = pt; return pt;
      });
    await this.page.mouse.click(pt.x, pt.y);
  }
  // tier=scene engine=echarts confidence=0.7 [scene: canvas/WebGL node — no DOM; addressed by identity]
  async feb(): Promise<void> {
    const pt = await this.page.evaluate(() => {
        const c = window.__echart;
        if (!c) throw new Error('scene/echarts: instance not found');
        const o = c.getOption();
        const cats = (o.xAxis && o.xAxis[0] && o.xAxis[0].data) || [];
        const i = cats.findIndex(v => String(v).toLowerCase() === "Feb".toLowerCase());
        if (i < 0) throw new Error('scene/echarts: no category ' + "Feb");
        const val = o.series[0].data[i];
        const p = c.convertToPixel({ seriesIndex: 0 }, [i, val]);
        const base = c.convertToPixel({ seriesIndex: 0 }, [i, 0]);
        const y = base ? (p[1] + base[1]) / 2 : p[1];
        const r = c.getDom().getBoundingClientRect();
        const pt = { x: Math.round(r.left + p[0]), y: Math.round(r.top + y) };
        window.__ksel = pt; return pt;
      });
    await this.page.mouse.click(pt.x, pt.y);
  }
}
