// AUTO-GENERATED by klew/scripts/export_pom.py — do not edit by hand.
// App: three-demo   Base URL: http://127.0.0.1:8123
// Generated from human-approved selectors (updated 2026-07-22).
import { type Page, type Locator } from '@playwright/test';

export class ObjectsPage {
  constructor(private readonly page: Page) {}

  // tier=scene engine=three confidence=0.7 [scene: canvas/WebGL node — no DOM; addressed by identity]
  async pyramid(): Promise<void> {
    const pt = await this.page.evaluate(() => {
        const t = window.__three;
        if (!t) throw new Error('scene/three: instance not found');
        const by = "name";
        const o = by === 'name' ? t.scene.getObjectByName("Pyramid")
                                : t.scene.getObjectByProperty(by, "Pyramid");
        if (!o) throw new Error('scene/three: no ' + by + '=' + "Pyramid");
        const v = o.getWorldPosition(new o.position.constructor());
        v.project(t.camera);
        const r = t.renderer.domElement.getBoundingClientRect();
        const pt = { x: Math.round(r.left + (v.x * 0.5 + 0.5) * r.width),
                     y: Math.round(r.top + (-v.y * 0.5 + 0.5) * r.height) };
        window.__ksel = pt; return pt;
      });
    await this.page.mouse.click(pt.x, pt.y);
  }
  // tier=scene engine=three confidence=0.7 [scene: canvas/WebGL node — no DOM; addressed by identity]
  async sphere(): Promise<void> {
    const pt = await this.page.evaluate(() => {
        const t = window.__three;
        if (!t) throw new Error('scene/three: instance not found');
        const by = "name";
        const o = by === 'name' ? t.scene.getObjectByName("Sphere")
                                : t.scene.getObjectByProperty(by, "Sphere");
        if (!o) throw new Error('scene/three: no ' + by + '=' + "Sphere");
        const v = o.getWorldPosition(new o.position.constructor());
        v.project(t.camera);
        const r = t.renderer.domElement.getBoundingClientRect();
        const pt = { x: Math.round(r.left + (v.x * 0.5 + 0.5) * r.width),
                     y: Math.round(r.top + (-v.y * 0.5 + 0.5) * r.height) };
        window.__ksel = pt; return pt;
      });
    await this.page.mouse.click(pt.x, pt.y);
  }
}
