// AUTO-GENERATED by klew/scripts/export_pom.py — do not edit by hand.
// App: fabric-demo   Base URL: http://127.0.0.1:8123
// Generated from human-approved selectors (updated 2026-07-22).
import { type Page, type Locator } from '@playwright/test';

export class ShapesPage {
  constructor(private readonly page: Page) {}

  // tier=scene engine=fabric confidence=0.7 [scene: canvas/WebGL node — no DOM; addressed by identity]
  async beta(): Promise<void> {
    const pt = await this.page.evaluate(() => {
        const c = window.__fabric;
        if (!c) throw new Error('scene/fabric: instance not found');
        const o = c.getObjects().find(o => String(o["name"]).toLowerCase() === "Beta".toLowerCase());
        if (!o) throw new Error('scene/fabric: no ' + "name" + '=' + "Beta");
        const cp = o.getCenterPoint();
        const v = c.viewportTransform;                       // scene -> screen (pan/zoom)
        const sx = cp.x * v[0] + cp.y * v[2] + v[4];
        const sy = cp.x * v[1] + cp.y * v[3] + v[5];
        const r = c.getElement().getBoundingClientRect();
        const pt = { x: Math.round(r.left + sx), y: Math.round(r.top + sy) };
        window.__ksel = pt; return pt;
      });
    await this.page.mouse.click(pt.x, pt.y);
  }
  // tier=scene engine=fabric confidence=0.7 [scene: canvas/WebGL node — no DOM; addressed by identity]
  async gamma(): Promise<void> {
    const pt = await this.page.evaluate(() => {
        const c = window.__fabric;
        if (!c) throw new Error('scene/fabric: instance not found');
        const o = c.getObjects().find(o => String(o["name"]).toLowerCase() === "Gamma".toLowerCase());
        if (!o) throw new Error('scene/fabric: no ' + "name" + '=' + "Gamma");
        const cp = o.getCenterPoint();
        const v = c.viewportTransform;                       // scene -> screen (pan/zoom)
        const sx = cp.x * v[0] + cp.y * v[2] + v[4];
        const sy = cp.x * v[1] + cp.y * v[3] + v[5];
        const r = c.getElement().getBoundingClientRect();
        const pt = { x: Math.round(r.left + sx), y: Math.round(r.top + sy) };
        window.__ksel = pt; return pt;
      });
    await this.page.mouse.click(pt.x, pt.y);
  }
}
