// AUTO-GENERATED by klew/scripts/export_pom.py — do not edit by hand.
// App: chartjs-demo   Base URL: http://127.0.0.1:8123
// Generated from human-approved selectors (updated 2026-07-22).
import { type Page, type Locator } from '@playwright/test';

export class BarsPage {
  constructor(private readonly page: Page) {}

  // tier=scene engine=chartjs confidence=0.7 [scene: canvas/WebGL node — no DOM; addressed by identity]
  async feb(): Promise<void> {
    const pt = await this.page.evaluate(() => {
        const c = window.__chart;
        if (!c) throw new Error('scene/chartjs: instance not found');
        const labels = c.data.labels.map(String);
        const i = labels.findIndex(l => l.toLowerCase() === "Feb".toLowerCase());
        if (i < 0) throw new Error('scene/chartjs: no label=Feb');
        const el = c.getDatasetMeta(0).data[i];
        const r = c.canvas.getBoundingClientRect();
        const y = el.base !== undefined ? (el.y + el.base) / 2 : el.y;  // inside bars
        const pt = { x: Math.round(r.left + el.x), y: Math.round(r.top + y) };
        window.__ksel = pt; return pt;
      });
    await this.page.mouse.click(pt.x, pt.y);
  }
  // tier=scene engine=chartjs confidence=0.7 [scene: canvas/WebGL node — no DOM; addressed by identity]
  async may(): Promise<void> {
    const pt = await this.page.evaluate(() => {
        const c = window.__chart;
        if (!c) throw new Error('scene/chartjs: instance not found');
        const labels = c.data.labels.map(String);
        const i = labels.findIndex(l => l.toLowerCase() === "May".toLowerCase());
        if (i < 0) throw new Error('scene/chartjs: no label=May');
        const el = c.getDatasetMeta(0).data[i];
        const r = c.canvas.getBoundingClientRect();
        const y = el.base !== undefined ? (el.y + el.base) / 2 : el.y;  // inside bars
        const pt = { x: Math.round(r.left + el.x), y: Math.round(r.top + y) };
        window.__ksel = pt; return pt;
      });
    await this.page.mouse.click(pt.x, pt.y);
  }
}
