// AUTO-GENERATED by klew/scripts/export_pom.py — do not edit by hand.
// App: todomvc   Base URL: http://127.0.0.1:8123/
// Generated from human-approved selectors (updated 2026-07-19).
import { type Page, type Locator } from '@playwright/test';

export class FilterPage {
  constructor(private readonly page: Page) {}

  // tier=role confidence=1.0
  get active(): Locator { return this.page.getByRole('link', { name: 'Active' }); }
  // tier=role confidence=1.0
  get all(): Locator { return this.page.getByRole('link', { name: 'All' }); }
  // tier=role confidence=1.0
  get completed(): Locator { return this.page.getByRole('link', { name: 'Completed' }); }
}

export class SearchPage {
  constructor(private readonly page: Page) {}

  // tier=role confidence=1.0
  get input(): Locator { return this.page.getByRole('searchbox', { name: 'Search todos' }); }
}

export class TodoPage {
  constructor(private readonly page: Page) {}

  // tier=role confidence=1.0
  get clearCompleted(): Locator { return this.page.getByRole('button', { name: 'Clear completed' }); }
  // tier=testid confidence=0.75 [a11y: non-user-facing locator]
  get count(): Locator { return this.page.getByTestId('todo-count'); }
  // tier=testid confidence=0.75 [a11y: non-user-facing locator]
  get list(): Locator { return this.page.getByTestId('todo-list'); }
  // tier=role confidence=1.0
  get newInput(): Locator { return this.page.getByRole('textbox', { name: 'New todo' }); }
  // tier=role confidence=1.0
  get toggleAll(): Locator { return this.page.getByRole('checkbox', { name: 'Mark all as complete' }); }
}
