// AUTO-GENERATED by klew/scripts/export_pom.py — do not edit by hand.
// App: phaser-demo   Base URL: http://127.0.0.1:8123
// Generated from human-approved selectors (updated 2026-07-22).
import { type Page, type Locator } from '@playwright/test';

export class SpritesPage {
  constructor(private readonly page: Page) {}

  // tier=scene engine=phaser confidence=0.7 [scene: canvas/WebGL node — no DOM; addressed by identity]
  async coin(): Promise<void> {
    const pt = await this.page.evaluate(() => {
        const s = window.__phaser;
        if (!s) throw new Error('scene/phaser: instance not found');
        const o = s.children.list.find(o => o["name"] != null &&
          String(o["name"]).toLowerCase() === "Coin".toLowerCase());
        if (!o) throw new Error('scene/phaser: no ' + "name" + '=' + "Coin");
        const cam = s.cameras.main;
        const r = s.game.canvas.getBoundingClientRect();
        const pt = { x: Math.round(r.left + (o.x - cam.scrollX) * cam.zoom),
                     y: Math.round(r.top + (o.y - cam.scrollY) * cam.zoom) };
        window.__ksel = pt; return pt;
      });
    await this.page.mouse.click(pt.x, pt.y);
  }
  // tier=scene engine=phaser confidence=0.7 [scene: canvas/WebGL node — no DOM; addressed by identity]
  async star(): Promise<void> {
    const pt = await this.page.evaluate(() => {
        const s = window.__phaser;
        if (!s) throw new Error('scene/phaser: instance not found');
        const o = s.children.list.find(o => o["name"] != null &&
          String(o["name"]).toLowerCase() === "Star".toLowerCase());
        if (!o) throw new Error('scene/phaser: no ' + "name" + '=' + "Star");
        const cam = s.cameras.main;
        const r = s.game.canvas.getBoundingClientRect();
        const pt = { x: Math.round(r.left + (o.x - cam.scrollX) * cam.zoom),
                     y: Math.round(r.top + (o.y - cam.scrollY) * cam.zoom) };
        window.__ksel = pt; return pt;
      });
    await this.page.mouse.click(pt.x, pt.y);
  }
}
