"""Render a run into the weekly markdown digest + backlog.json sidecar. Pure.

`build_model()` turns run state into a plain dict; `render_markdown()` turns that
dict into the document. The digest is auto-published to GitHub Pages on merge, so:

  * links are emitted ONLY for http(s) URLs — anything else renders as plain text
  * no absolute home paths, no secrets, no raw fetched HTML ever reach the page
  * nothing is silently absent: failed sources, skipped clusters and below-bar
    ideas all get their own lines
"""

from __future__ import annotations

import json
import re
from datetime import datetime
from urllib.parse import urlparse

from qe_signals.models import Cluster, IdeaResult, Signal, SourceHealth

FOOTER = (
    "_Generated by `qe_signals/run.py`. Ideas are LLM-drafted against `dna_playbook.md`; "
    "the merge of this file is the human approval._"
)
_HTML_TAG = re.compile(r"<[^>]+>")


def digest_filename(run_date: datetime) -> str:
    iso = run_date.isocalendar()
    return f"{iso.year}-W{iso.week:02d}-digest.md"


def safe_link(text: str, url: str) -> str:
    """Markdown link for http(s) only; other schemes become escaped plain text."""
    scheme = urlparse(url).scheme.lower()
    t = _clean(text)
    if scheme in ("http", "https"):
        return f"[{t}]({url})"
    return f"{t} (`{_clean(url)}`)"


def _clean(text: str) -> str:
    """Strip tags, collapse whitespace, escape the few characters that break tables/links."""
    t = _HTML_TAG.sub(" ", text or "")
    t = re.sub(r"\s+", " ", t).strip()
    return t.replace("|", "\\|").replace("[", "\\[").replace("]", "\\]")


def build_model(
    *,
    run_id: str,
    now: datetime,
    since: datetime,
    window_note: str,
    model: str,
    playbook_sha: str,
    health: list[SourceHealth],
    signals: dict[str, Signal],
    scores: dict[str, dict],
    clusters: list[Cluster],
    results: list[IdeaResult],
    skipped_seen: list[Cluster],
    skipped_budget: list[Cluster],
    prior_run: str | None,
    notes: list[str],
    top_per_cluster: int = 3,
) -> dict:
    ok = [h for h in health if h.status == "ok"]
    failed = [h for h in health if h.status == "failed"]
    empty = [h for h in health if h.status == "empty"]
    ideas = []
    for r in results:
        if r.best is None:
            ideas.append(
                {
                    "cluster": r.cluster_key,
                    "title": None,
                    "score": None,
                    "met_bar": False,
                    "iterations": len(r.iterations),
                    "reason": r.reason,
                }
            )
            continue
        ev = []
        for sid in r.best.evidence:
            s = signals.get(sid)
            ev.append({"id": sid, "title": s.title if s else None, "url": s.url if s else None})
        ideas.append(
            {
                "cluster": r.cluster_key,
                "title": r.best.title,
                "score": r.best_score,
                "met_bar": r.met_bar,
                "iterations": len(r.iterations),
                "extends": r.best.extends,
                "quality_metric": r.best.quality_metric,
                "problem": r.best.problem,
                "who_hurts": r.best.who_hurts,
                "proposal": r.best.proposal,
                "smallest_slice": r.best.smallest_slice,
                "evidence": ev,
                "reason": r.reason,
            }
        )
    cl = []
    for c in clusters:
        top = []
        for sid in c.member_ids[:top_per_cluster]:
            s = signals.get(sid)
            if s:
                top.append(
                    {
                        "id": sid,
                        "title": s.title,
                        "url": s.url,
                        "source": s.source,
                        "score": scores.get(sid, {}).get("score", 0.0),
                    }
                )
        cl.append({"key_term": c.key_term, "size": len(c.member_ids), "top": top})
    return {
        "run_id": run_id,
        "generated": now.isoformat(timespec="seconds"),
        "since": since.isoformat(timespec="seconds"),
        "window_note": window_note,
        "model": model,
        "playbook_sha": playbook_sha,
        "prior_run": prior_run,
        "sources_ok": len(ok),
        "sources_empty": len(empty),
        "sources_failed": len(failed),
        "signals": len(signals),
        "ideas": len([i for i in ideas if i["title"]]),
        "ideas_met_bar": len([i for i in ideas if i["met_bar"]]),
        "health": [h.model_dump() for h in health],
        "clusters": cl,
        "idea_list": ideas,
        "skipped_seen": [c.key_term for c in skipped_seen],
        "skipped_budget": [c.key_term for c in skipped_budget],
        "notes": list(notes),
    }


def render_markdown(m: dict) -> str:
    out: list[str] = []
    fm = {
        k: m[k]
        for k in (
            "run_id",
            "generated",
            "since",
            "model",
            "playbook_sha",
            "prior_run",
            "sources_ok",
            "sources_empty",
            "sources_failed",
            "signals",
            "ideas",
            "ideas_met_bar",
        )
    }
    out.append("---")
    for k, v in fm.items():
        out.append(f"{k}: {json.dumps(v)}")
    out.append("---")
    out.append("")
    out.append(f"# QE signals digest — {m['generated'][:10]}")
    out.append("")
    out.append(f"**Window:** since {m['since'][:16]} — {_clean(m['window_note'])}")
    if m["notes"]:
        out.append("")
        for n in m["notes"]:
            out.append(f"- note: {_clean(n)}")
    out.append("")

    out.append("## Source health")
    out.append("")
    out.append("| Source | Status | Items | Undated | Note |")
    out.append("|---|---|---:|---:|---|")
    for h in m["health"]:
        out.append(
            f"| {_clean(h['name'])} | {h['status']} | {h['items']} | {h['undated']} | "
            f"{_clean(h['error'])} |"
        )
    out.append("")

    out.append("## Top signals per cluster")
    out.append("")
    if not m["clusters"]:
        out.append("_No signals this week._")
    for c in m["clusters"]:
        out.append(f"### {_clean(c['key_term'])} ({c['size']})")
        for t in c["top"]:
            out.append(f"- {safe_link(t['title'], t['url'])} — {t['source']} · {t['score']:.2f}")
        out.append("")

    out.append("## Idea backlog")
    out.append("")
    if not m["idea_list"]:
        out.append("_No ideas generated this run._")
    for i, idea in enumerate(m["idea_list"], 1):
        if not idea["title"]:
            out.append(
                f"### {i}. (no idea for cluster `{_clean(idea['cluster'])}`) — {idea['reason']}"
            )
            out.append("")
            continue
        tag = "" if idea["met_bar"] else " · **below bar**"
        out.append(
            f"### {i}. {_clean(idea['title'])} — {idea['score']:.0f}/100"
            f" · {idea['iterations']} iter · extends `{idea['extends']}`{tag}"
        )
        out.append(f"- **Problem:** {_clean(idea['problem'])}")
        out.append(f"- **Who hurts:** {_clean(idea['who_hurts'])}")
        out.append(f"- **Proposal:** {_clean(idea['proposal'])}")
        out.append(f"- **Quality metric:** {_clean(idea['quality_metric'])}")
        out.append(f"- **Smallest slice:** {_clean(idea['smallest_slice'])}")
        ev = []
        for e in idea["evidence"]:
            if e["title"] and e["url"]:
                ev.append(safe_link(e["title"], e["url"]))
            else:
                ev.append(f"`{_clean(e['id'])}`")
        out.append(f"- **Evidence:** {', '.join(ev) if ev else '_none_'}")
        out.append("")

    if m["skipped_seen"] or m["skipped_budget"]:
        out.append("## Skipped clusters")
        out.append("")
        for k in m["skipped_seen"]:
            out.append(f"- `{_clean(k)}` — already ideated in the previous run")
        for k in m["skipped_budget"]:
            out.append(f"- `{_clean(k)}` — LLM call budget exhausted")
        out.append("")

    failed = [h for h in m["health"] if h["status"] == "failed"]
    if failed:
        out.append("## Failed sources")
        out.append("")
        for h in failed:
            out.append(f"- `{_clean(h['name'])}` — {_clean(h['error'])}")
        out.append("")

    out.append(FOOTER)
    out.append("")
    return "\n".join(out)


def backlog_json(m: dict, results: list[IdeaResult]) -> str:
    return json.dumps(
        {
            "run_id": m["run_id"],
            "generated": m["generated"],
            "results": [r.model_dump(mode="json") for r in results],
        },
        indent=1,
    )
