// AUTO-GENERATED by klew/scripts/export_pom.py — do not edit by hand.
// App: pixi-demo   Base URL: http://127.0.0.1:8123
// Generated from human-approved selectors (updated 2026-07-22).
import { type Page, type Locator } from '@playwright/test';

export class NodesPage {
  constructor(private readonly page: Page) {}

  // tier=scene engine=pixi confidence=0.7 [scene: canvas/WebGL node — no DOM; addressed by identity]
  async three(): Promise<void> {
    const pt = await this.page.evaluate(() => {
        const app = window.__PIXI_APP__;
        if (!app) throw new Error('scene/pixi: instance not found');
        const stack = [...app.stage.children]; let hit = null; while (stack.length) { const n = stack.pop(); if (n["label"] != null && String(n["label"]).toLowerCase() === "Three".toLowerCase()) { hit = n; break; } if (n.children) stack.push(...n.children); }
        if (!hit) throw new Error('scene/pixi: no ' + "label" + '=' + "Three");
        const g = hit.getGlobalPosition();
        const r = app.canvas.getBoundingClientRect();
        const pt = { x: Math.round(r.left + g.x), y: Math.round(r.top + g.y) };
        window.__ksel = pt; return pt;
      });
    await this.page.mouse.click(pt.x, pt.y);
  }
  // tier=scene engine=pixi confidence=0.7 [scene: canvas/WebGL node — no DOM; addressed by identity]
  async two(): Promise<void> {
    const pt = await this.page.evaluate(() => {
        const app = window.__PIXI_APP__;
        if (!app) throw new Error('scene/pixi: instance not found');
        const stack = [...app.stage.children]; let hit = null; while (stack.length) { const n = stack.pop(); if (n["label"] != null && String(n["label"]).toLowerCase() === "Two".toLowerCase()) { hit = n; break; } if (n.children) stack.push(...n.children); }
        if (!hit) throw new Error('scene/pixi: no ' + "label" + '=' + "Two");
        const g = hit.getGlobalPosition();
        const r = app.canvas.getBoundingClientRect();
        const pt = { x: Math.round(r.left + g.x), y: Math.round(r.top + g.y) };
        window.__ksel = pt; return pt;
      });
    await this.page.mouse.click(pt.x, pt.y);
  }
}
