// AUTO-GENERATED by klew/scripts/export_pom.py — do not edit by hand.
// App: saucedemo   Base URL: https://www.saucedemo.com/
// Generated from human-approved selectors (updated 2026-07-19).
import { type Page, type Locator } from '@playwright/test';

export class CartPage {
  constructor(private readonly page: Page) {}

  // tier=testid confidence=0.75 [a11y: non-user-facing locator]
  get badge(): Locator { return this.page.getByTestId('shopping-cart-badge'); }
}

export class InventoryPage {
  constructor(private readonly page: Page) {}

  // tier=testid confidence=0.75 [a11y: non-user-facing locator]
  get addBackpack(): Locator { return this.page.getByTestId('add-to-cart-sauce-labs-backpack'); }
}

export class LoginPage {
  constructor(private readonly page: Page) {}

  // tier=label-text confidence=0.9
  get password(): Locator { return this.page.getByPlaceholder('Password'); }
  // tier=role confidence=1.0
  get submit(): Locator { return this.page.getByRole('button', { name: 'Login' }); }
  // tier=role confidence=1.0
  get username(): Locator { return this.page.getByRole('textbox', { name: 'Username' }); }
}
