// AUTO-GENERATED by klew/scripts/export_pom.py — do not edit by hand.
// App: cytoscape-demo   Base URL: http://127.0.0.1:8123
// Generated from human-approved selectors (updated 2026-07-22).
import { type Page, type Locator } from '@playwright/test';

export class NodesPage {
  constructor(private readonly page: Page) {}

  // tier=scene engine=cytoscape confidence=0.7 [scene: canvas/WebGL node — no DOM; addressed by identity]
  async b(): Promise<void> {
    const pt = await this.page.evaluate(() => {
        const cy = window.__cy;
        if (!cy) throw new Error('scene/cytoscape: instance not found');
        const by = "label", val = "Node B"; const node = by === 'id' ? cy.getElementById(val) : cy.nodes().filter(n => String(n.data(by)).toLowerCase() === val.toLowerCase())[0]; 
        if (!node || node.length === 0)
          throw new Error('scene/cytoscape: no ' + by + '=' + val);
        const rp = node.renderedPosition();
        const r = cy.container().getBoundingClientRect();
        const pt = { x: Math.round(r.left + rp.x), y: Math.round(r.top + rp.y) };
        window.__ksel = pt; return pt;
      });
    await this.page.mouse.click(pt.x, pt.y);
  }
  // tier=scene engine=cytoscape confidence=0.7 [scene: canvas/WebGL node — no DOM; addressed by identity]
  async c(): Promise<void> {
    const pt = await this.page.evaluate(() => {
        const cy = window.__cy;
        if (!cy) throw new Error('scene/cytoscape: instance not found');
        const by = "label", val = "Node C"; const node = by === 'id' ? cy.getElementById(val) : cy.nodes().filter(n => String(n.data(by)).toLowerCase() === val.toLowerCase())[0]; 
        if (!node || node.length === 0)
          throw new Error('scene/cytoscape: no ' + by + '=' + val);
        const rp = node.renderedPosition();
        const r = cy.container().getBoundingClientRect();
        const pt = { x: Math.round(r.left + rp.x), y: Math.round(r.top + rp.y) };
        window.__ksel = pt; return pt;
      });
    await this.page.mouse.click(pt.x, pt.y);
  }
}
