// AUTO-GENERATED by klew/scripts/export_pom.py — do not edit by hand.
// App: sigma-demo   Base URL: http://127.0.0.1:8123
// Generated from human-approved selectors (updated 2026-07-22).
import { type Page, type Locator } from '@playwright/test';

export class GraphPage {
  constructor(private readonly page: Page) {}

  // tier=scene engine=sigma confidence=0.7 [scene: canvas/WebGL node — no DOM; addressed by identity]
  async alice(): Promise<void> {
    const pt = await this.page.evaluate(() => {
        const s = window.__sigma;
        if (!s) throw new Error('scene/sigma: instance not found');
        const g = s.getGraph();
        const id = g.findNode((n, a) => String(a["label"]).toLowerCase() === "Alice".toLowerCase());
        if (!id) throw new Error('scene/sigma: no label=Alice');
        const a = g.getNodeAttributes(id);
        const vp = s.graphToViewport({ x: a.x, y: a.y });
        const r = s.getContainer().getBoundingClientRect();
        const pt = { x: Math.round(r.left + vp.x), y: Math.round(r.top + vp.y) };
        window.__ksel = pt; return pt;
      });
    await this.page.mouse.click(pt.x, pt.y);
  }
  // tier=scene engine=sigma confidence=0.7 [scene: canvas/WebGL node — no DOM; addressed by identity]
  async bob(): Promise<void> {
    const pt = await this.page.evaluate(() => {
        const s = window.__sigma;
        if (!s) throw new Error('scene/sigma: instance not found');
        const g = s.getGraph();
        const id = g.findNode((n, a) => String(a["label"]).toLowerCase() === "Bob".toLowerCase());
        if (!id) throw new Error('scene/sigma: no label=Bob');
        const a = g.getNodeAttributes(id);
        const vp = s.graphToViewport({ x: a.x, y: a.y });
        const r = s.getContainer().getBoundingClientRect();
        const pt = { x: Math.round(r.left + vp.x), y: Math.round(r.top + vp.y) };
        window.__ksel = pt; return pt;
      });
    await this.page.mouse.click(pt.x, pt.y);
  }
}

export class SearchPage {
  constructor(private readonly page: Page) {}

  // tier=testid confidence=0.75 [a11y: non-user-facing locator]
  get input(): Locator { return this.page.getByTestId('node-search'); }
}
