#!/usr/bin/env python3
"""Export an approved selector cache to a Playwright Page Object Model (TS).

Closes the loop with the repo's other skills: web-ui-explorer resolves
human-approved, runtime-verified locators; this turns them into a typed Page
Object so `yilsf`-generated specs import real selectors instead of guessing, and
`testguard` can review specs built on them.

    export_pom.py --app <slug> [--out path.ts] [--min-confidence 0.0]

Logical names group into classes by their first dotted segment:
    login.email        -> class LoginPage   { get email()  }
    login.submit       -> class LoginPage   { get submit() }
    checkout.placeOrder-> class CheckoutPage { get placeOrder() }

`getBy*` selectors pass through as `this.page.getBy...`; raw CSS becomes
`this.page.locator('...')`. Stale/ambiguous or low-confidence entries are
skipped (and reported) so the POM only exposes locators worth trusting.
"""
from __future__ import annotations

import argparse
import sys

from _common import app_dir, load_cache


def _member(rest: list[str]) -> str:
    parts = [p for seg in rest for p in seg.replace("-", "_").split("_")]
    if not parts:
        return "el"
    head, *tail = parts
    name = head + "".join(w[:1].upper() + w[1:] for w in tail)
    return name if name.isidentifier() else "_" + name


def _class_name(group: str) -> str:
    words = group.replace("-", "_").split("_")
    return "".join(w[:1].upper() + w[1:] for w in words if w) + "Page"


def _locator_expr(selector: str) -> str:
    s = selector.strip()
    if s.startswith("getBy"):
        return f"this.page.{s}"
    css = s.replace("\\", "\\\\").replace("'", "\\'")
    return f"this.page.locator('{css}')"


def main() -> None:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("--app", required=True, help="application slug")
    ap.add_argument("--out", default=None, help="output .ts path (default under knowledge/<app>/)")
    ap.add_argument(
        "--min-confidence", type=float, default=0.0, help="skip entries below this score"
    )
    args = ap.parse_args()

    cache = load_cache(args.app)
    selectors = cache.get("selectors", {})
    if not selectors:
        sys.exit(f"error: no selectors cached for app {args.app!r}")

    groups: dict[str, list[tuple[str, dict]]] = {}
    skipped: list[str] = []
    for name, entry in sorted(selectors.items()):
        if entry.get("status") in {"stale", "ambiguous"}:
            skipped.append(f"{name} ({entry['status']})")
            continue
        if float(entry.get("confidence", 1.0)) < args.min_confidence:
            skipped.append(f"{name} (confidence {entry.get('confidence')})")
            continue
        group, *rest = name.split(".")
        groups.setdefault(group, []).append((_member(rest or [group]), entry))

    if not groups:
        sys.exit("error: nothing to export after filtering (all stale/ambiguous/low-confidence)")

    lines = [
        "// AUTO-GENERATED by web-ui-explorer/scripts/export_pom.py — do not edit by hand.",
        f"// App: {cache.get('app', args.app)}   Base URL: {cache.get('base_url', '')}",
        f"// Generated from human-approved selectors (updated {cache.get('updated', '')}).",
        "import { type Page, type Locator } from '@playwright/test';",
        "",
    ]
    for group in sorted(groups):
        lines.append(f"export class {_class_name(group)} {{")
        lines.append("  constructor(private readonly page: Page) {}")
        lines.append("")
        seen: set[str] = set()
        for member, entry in groups[group]:
            m = member
            n = 1
            while m in seen:  # guard against camelCase collisions
                n += 1
                m = f"{member}{n}"
            seen.add(m)
            note = f"  // tier={entry.get('tier')} confidence={entry.get('confidence')}"
            if entry.get("a11y_flag"):
                note += " [a11y: non-user-facing locator]"
            lines.append(note)
            lines.append(f"  get {m}(): Locator {{ return {_locator_expr(entry['selector'])}; }}")
        lines.append("}")
        lines.append("")

    out = args.out or str(app_dir(args.app) / f"{args.app}.pom.ts")
    app_dir(args.app).mkdir(parents=True, exist_ok=True)
    with open(out, "w") as fh:
        fh.write("\n".join(lines))

    print(f"Wrote {out}")
    print(f"  classes: {', '.join(_class_name(g) for g in sorted(groups))}")
    if skipped:
        print(f"  skipped: {', '.join(skipped)}")


if __name__ == "__main__":
    main()
